/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana.coordinador;

import ventana.secretaria.SistemaPrincipalSecretaria;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Edder
 */
public class RegistroNiñosCoordinador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaNiños
     */
    public RegistroNiñosCoordinador() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/logo3.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CAPsys");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/rosa.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre_niño_registro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido_niño_registro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edad_niño_registro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sexo_niño_registro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lugar_nacimiento_niño_registro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fecha_nacimiento_niño_registro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        escolaridad_niño_registro = new javax.swing.JTextField();
        direccion_niño_registro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivo_consulta_niño_registro = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        referencia_niño_registro = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnostico_niño_registro = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        prenatal_registro = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        posnatal_registro = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        desarrollo_psicomotor_registro = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        situacion_actual_niño_registro = new javax.swing.JTextArea();
        alimentacion_registro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        sueño_registro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        aseo_personal_registro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        emocional_registro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        limites_establecedor_registro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        limites_ejecutor_registro = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        apariencia_general_niño_registro = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        recomendaciones_niño_registro = new javax.swing.JTextField();
        registrar_niños = new javax.swing.JButton();
        salir_niños = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Datos de Identificación");

        jLabel2.setText("Nombres:");

        nombre_niño_registro.setEditable(false);
        nombre_niño_registro.setFocusCycleRoot(true);

        jLabel3.setText("Apellidos:");

        apellido_niño_registro.setEditable(false);
        apellido_niño_registro.setFocusCycleRoot(true);

        jLabel5.setText("Edad:");

        edad_niño_registro.setEditable(false);
        edad_niño_registro.setFocusCycleRoot(true);

        jLabel6.setText("Sexo:");

        sexo_niño_registro.setEditable(false);
        sexo_niño_registro.setFocusCycleRoot(true);

        jLabel7.setText("Lugar de Nacimiento:");

        lugar_nacimiento_niño_registro.setEditable(false);
        lugar_nacimiento_niño_registro.setFocusCycleRoot(true);

        jLabel8.setText("Fecha de Nacimiento:");

        fecha_nacimiento_niño_registro.setEditable(false);
        fecha_nacimiento_niño_registro.setFocusCycleRoot(true);

        jLabel9.setText("Escolaridad:");

        jLabel10.setText("Dirección:");

        escolaridad_niño_registro.setEditable(false);
        escolaridad_niño_registro.setFocusCycleRoot(true);

        direccion_niño_registro.setEditable(false);
        direccion_niño_registro.setFocusCycleRoot(true);

        jLabel11.setText("Motivo de la Consulta:");

        motivo_consulta_niño_registro.setEditable(false);
        motivo_consulta_niño_registro.setColumns(20);
        motivo_consulta_niño_registro.setLineWrap(true);
        motivo_consulta_niño_registro.setRows(5);
        motivo_consulta_niño_registro.setFocusCycleRoot(true);
        jScrollPane1.setViewportView(motivo_consulta_niño_registro);

        jLabel12.setText("Referencia:");

        referencia_niño_registro.setEditable(false);
        referencia_niño_registro.setColumns(20);
        referencia_niño_registro.setLineWrap(true);
        referencia_niño_registro.setRows(5);
        referencia_niño_registro.setFocusCycleRoot(true);
        jScrollPane2.setViewportView(referencia_niño_registro);

        jLabel13.setText("ID(diagnostico):");

        diagnostico_niño_registro.setEditable(false);
        diagnostico_niño_registro.setColumns(20);
        diagnostico_niño_registro.setLineWrap(true);
        diagnostico_niño_registro.setRows(5);
        diagnostico_niño_registro.setFocusCycleRoot(true);
        jScrollPane3.setViewportView(diagnostico_niño_registro);

        jLabel14.setText("Prenatal:");

        prenatal_registro.setEditable(false);
        prenatal_registro.setColumns(20);
        prenatal_registro.setLineWrap(true);
        prenatal_registro.setRows(5);
        prenatal_registro.setFocusCycleRoot(true);
        jScrollPane4.setViewportView(prenatal_registro);

        jLabel15.setText("Posnatal:");

        posnatal_registro.setEditable(false);
        posnatal_registro.setColumns(20);
        posnatal_registro.setLineWrap(true);
        posnatal_registro.setRows(5);
        posnatal_registro.setFocusCycleRoot(true);
        jScrollPane5.setViewportView(posnatal_registro);

        jLabel16.setText("Desarrollo Psicomotor:");

        desarrollo_psicomotor_registro.setEditable(false);
        desarrollo_psicomotor_registro.setColumns(20);
        desarrollo_psicomotor_registro.setLineWrap(true);
        desarrollo_psicomotor_registro.setRows(5);
        desarrollo_psicomotor_registro.setFocusCycleRoot(true);
        jScrollPane6.setViewportView(desarrollo_psicomotor_registro);

        jLabel17.setText("Alimentación:");

        situacion_actual_niño_registro.setEditable(false);
        situacion_actual_niño_registro.setColumns(20);
        situacion_actual_niño_registro.setLineWrap(true);
        situacion_actual_niño_registro.setRows(5);
        situacion_actual_niño_registro.setFocusCycleRoot(true);
        jScrollPane7.setViewportView(situacion_actual_niño_registro);

        alimentacion_registro.setEditable(false);
        alimentacion_registro.setFocusCycleRoot(true);

        jLabel18.setText("Sueño:");

        sueño_registro.setEditable(false);
        sueño_registro.setFocusCycleRoot(true);

        jLabel19.setText("Aseo Personal:");

        aseo_personal_registro.setEditable(false);
        aseo_personal_registro.setFocusCycleRoot(true);

        jLabel20.setText("Emocional:");

        emocional_registro.setEditable(false);
        emocional_registro.setFocusCycleRoot(true);

        jLabel21.setText("¿Quién establece los límites?:");

        limites_establecedor_registro.setEditable(false);
        limites_establecedor_registro.setFocusCycleRoot(true);

        jLabel22.setText("¿Quién los ejecuta?:");

        limites_ejecutor_registro.setEditable(false);
        limites_ejecutor_registro.setFocusCycleRoot(true);

        jLabel23.setText("Situación Actual:");

        jLabel24.setText("Apariencia General:");

        apariencia_general_niño_registro.setEditable(false);
        apariencia_general_niño_registro.setFocusCycleRoot(true);

        jLabel25.setText("Recomendaciones:");

        recomendaciones_niño_registro.setEditable(false);
        recomendaciones_niño_registro.setFocusCycleRoot(true);

        registrar_niños.setBackground(new java.awt.Color(255, 153, 153));
        registrar_niños.setText("Buscar");
        registrar_niños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_niñosActionPerformed(evt);
            }
        });

        salir_niños.setBackground(new java.awt.Color(255, 153, 153));
        salir_niños.setText("Regresar");
        salir_niños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_niñosActionPerformed(evt);
            }
        });

        jLabel26.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellido_niño_registro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(edad_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(sexo_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lugar_nacimiento_niño_registro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_nacimiento_niño_registro))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(direccion_niño_registro)
                                    .addComponent(escolaridad_niño_registro)))
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane4)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane5)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alimentacion_registro)
                                            .addComponent(sueño_registro)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aseo_personal_registro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(emocional_registro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(limites_establecedor_registro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(limites_ejecutor_registro))
                                    .addComponent(jLabel23)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(apariencia_general_niño_registro)
                                            .addComponent(recomendaciones_niño_registro))))
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(salir_niños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(registrar_niños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(alimentacion_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(sueño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(aseo_personal_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(emocional_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(limites_establecedor_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(limites_ejecutor_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel23)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellido_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edad_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(sexo_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lugar_nacimiento_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(fecha_nacimiento_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(escolaridad_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(direccion_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(apariencia_general_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(recomendaciones_niño_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registrar_niños)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salir_niños)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_niñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_niñosActionPerformed
        SistemaPrincipalCoordinador ventana = new SistemaPrincipalCoordinador();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_salir_niñosActionPerformed

    private void registrar_niñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_niñosActionPerformed
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_niños where Indice = ?");
            
            pst.setString(1, buscar.getText().trim());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                nombre_niño_registro.setText(rs.getString("Nombres"));
                apellido_niño_registro.setText(rs.getString("Apellidos"));
                edad_niño_registro.setText(rs.getString("Edad"));
                sexo_niño_registro.setText(rs.getString("Sexo"));
                lugar_nacimiento_niño_registro.setText(rs.getString("LugarDeNacimiento"));
                fecha_nacimiento_niño_registro.setText(rs.getString("FechaDeNacimiento"));
                escolaridad_niño_registro.setText(rs.getString("Escolaridad"));
                direccion_niño_registro.setText(rs.getString("Direccion"));
                motivo_consulta_niño_registro.setText(rs.getString("MotivoConsulta"));
                referencia_niño_registro.setText(rs.getString("Referencia"));
                diagnostico_niño_registro.setText(rs.getString("ID(diagnostico)"));
                prenatal_registro.setText(rs.getString("Prenatal"));
                posnatal_registro.setText(rs.getString("Posnatal"));
                desarrollo_psicomotor_registro.setText(rs.getString("DesarrolloPsicomotor"));
                alimentacion_registro.setText(rs.getString("Alimentacion"));
                sueño_registro.setText(rs.getString("Sueño"));
                aseo_personal_registro.setText(rs.getString("AseoPersonal"));
                emocional_registro.setText(rs.getString("Emocional"));
                limites_establecedor_registro.setText(rs.getString("LimitesEstablecedor"));
                limites_ejecutor_registro.setText(rs.getString("LimitesEjecutor"));
                situacion_actual_niño_registro.setText(rs.getString("SituacionActual"));
                apariencia_general_niño_registro.setText(rs.getString("AparienciaGeneral"));
                recomendaciones_niño_registro.setText(rs.getString("Recomendaciones"));
            } else{
                JOptionPane.showMessageDialog(null, "Este registro no existe.");
            }
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_registrar_niñosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroNiñosCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroNiñosCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroNiñosCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroNiñosCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroNiñosCoordinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alimentacion_registro;
    private javax.swing.JTextField apariencia_general_niño_registro;
    private javax.swing.JTextField apellido_niño_registro;
    private javax.swing.JTextField aseo_personal_registro;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextArea desarrollo_psicomotor_registro;
    private javax.swing.JTextArea diagnostico_niño_registro;
    private javax.swing.JTextField direccion_niño_registro;
    private javax.swing.JTextField edad_niño_registro;
    private javax.swing.JTextField emocional_registro;
    private javax.swing.JTextField escolaridad_niño_registro;
    private javax.swing.JTextField fecha_nacimiento_niño_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField limites_ejecutor_registro;
    private javax.swing.JTextField limites_establecedor_registro;
    private javax.swing.JTextField lugar_nacimiento_niño_registro;
    private javax.swing.JTextArea motivo_consulta_niño_registro;
    private javax.swing.JTextField nombre_niño_registro;
    private javax.swing.JTextArea posnatal_registro;
    private javax.swing.JTextArea prenatal_registro;
    private javax.swing.JTextField recomendaciones_niño_registro;
    private javax.swing.JTextArea referencia_niño_registro;
    private javax.swing.JButton registrar_niños;
    private javax.swing.JButton salir_niños;
    private javax.swing.JTextField sexo_niño_registro;
    private javax.swing.JTextArea situacion_actual_niño_registro;
    private javax.swing.JTextField sueño_registro;
    // End of variables declaration//GEN-END:variables
}
