/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana.coordinador;

import java.sql.*;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventana.secretaria.SistemaPrincipalSecretaria;

/**
 *
 * @author Edder
 */
public class VentanaNiñosCoordinador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaNiños
     */
    public VentanaNiñosCoordinador() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/logo3.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CAPsys");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/rosa.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre_niño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido_niño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edad_niño = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lugar_nacimiento_niño = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        escolaridad_niño = new javax.swing.JTextField();
        direccion_niño = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivo_consulta_niño = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        referencia_niño = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnostico_niño = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        prenatal = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        posnatal = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        desarrollo_psicomotor = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        situacion_actual_niño = new javax.swing.JTextArea();
        alimentacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        sueño = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        aseo_personal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        emocional = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        limites_establecedor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        limites_ejecutor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        apariencia_general_niño = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        recomendaciones_niño = new javax.swing.JTextField();
        registrar_niños = new javax.swing.JButton();
        salir_niños = new javax.swing.JButton();
        sexo_niños = new javax.swing.JComboBox<>();
        etiquetaLoca2 = new javax.swing.JLabel();
        etiquetaLocas = new javax.swing.JLabel();
        fecha_nacimiento_niños = new com.toedter.calendar.JDateChooser();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Datos de Identificación");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellidos:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Sexo:");

        jLabel7.setText("Lugar de Nacimiento:");

        jLabel8.setText("Fecha de Nacimiento:");

        jLabel9.setText("Escolaridad:");

        jLabel10.setText("Dirección:");

        jLabel11.setText("Motivo de la Consulta:");

        motivo_consulta_niño.setColumns(20);
        motivo_consulta_niño.setLineWrap(true);
        motivo_consulta_niño.setRows(5);
        jScrollPane1.setViewportView(motivo_consulta_niño);

        jLabel12.setText("Referencia:");

        referencia_niño.setColumns(20);
        referencia_niño.setLineWrap(true);
        referencia_niño.setRows(5);
        jScrollPane2.setViewportView(referencia_niño);

        jLabel13.setText("ID(diagnostico):");

        diagnostico_niño.setColumns(20);
        diagnostico_niño.setLineWrap(true);
        diagnostico_niño.setRows(5);
        jScrollPane3.setViewportView(diagnostico_niño);

        jLabel14.setText("Prenatal:");

        prenatal.setColumns(20);
        prenatal.setLineWrap(true);
        prenatal.setRows(5);
        jScrollPane4.setViewportView(prenatal);

        jLabel15.setText("Posnatal:");

        posnatal.setColumns(20);
        posnatal.setLineWrap(true);
        posnatal.setRows(5);
        jScrollPane5.setViewportView(posnatal);

        jLabel16.setText("Desarrollo Psicomotor:");

        desarrollo_psicomotor.setColumns(20);
        desarrollo_psicomotor.setLineWrap(true);
        desarrollo_psicomotor.setRows(5);
        jScrollPane6.setViewportView(desarrollo_psicomotor);

        jLabel17.setText("Alimentación:");

        situacion_actual_niño.setColumns(20);
        situacion_actual_niño.setLineWrap(true);
        situacion_actual_niño.setRows(5);
        jScrollPane7.setViewportView(situacion_actual_niño);

        jLabel18.setText("Sueño:");

        jLabel19.setText("Aseo Personal:");

        jLabel20.setText("Emocional:");

        jLabel21.setText("¿Quién establece los límites?:");

        jLabel22.setText("¿Quién los ejecuta?:");

        jLabel23.setText("Situación Actual:");

        jLabel24.setText("Apariencia General:");

        jLabel25.setText("Recomendaciones:");

        registrar_niños.setBackground(new java.awt.Color(255, 153, 153));
        registrar_niños.setText("Registrar");
        registrar_niños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_niñosActionPerformed(evt);
            }
        });

        salir_niños.setBackground(new java.awt.Color(255, 153, 153));
        salir_niños.setText("Regresar");
        salir_niños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_niñosActionPerformed(evt);
            }
        });

        sexo_niños.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        etiquetaLocas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellido_niño)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edad_niño, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sexo_niños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lugar_nacimiento_niño))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccion_niño)
                            .addComponent(escolaridad_niño)))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(2, 2, 2)
                                .addComponent(fecha_nacimiento_niños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre_niño, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alimentacion)
                                    .addComponent(sueño)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aseo_personal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(emocional))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limites_establecedor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limites_ejecutor))
                            .addComponent(jLabel23)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apariencia_general_niño)
                                    .addComponent(recomendaciones_niño))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(registrar_niños))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaLocas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaLoca2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir_niños, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(alimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(apellido_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(edad_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(sexo_niños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lugar_nacimiento_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(fecha_nacimiento_niños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(escolaridad_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(direccion_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(sueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(aseo_personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(emocional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(limites_establecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(limites_ejecutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(jLabel23)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(apariencia_general_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(recomendaciones_niño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registrar_niños)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salir_niños)
                            .addComponent(etiquetaLoca2)
                            .addComponent(etiquetaLocas))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_niñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_niñosActionPerformed
        SistemaPrincipalCoordinador ventana = new SistemaPrincipalCoordinador();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_salir_niñosActionPerformed

    private void registrar_niñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_niñosActionPerformed
       
        String sexo = (String) sexo_niños.getSelectedItem();
        Date date = fecha_nacimiento_niños.getDate();
        long d = date.getTime();
        java.sql.Date date2 = new java.sql.Date(d);
        String fecha = date2.toString();
        
        String nombre = nombre_niño.getText();
        String apellido = apellido_niño.getText();
        String edad = edad_niño.getText();
        String lugarNacimiento = lugar_nacimiento_niño.getText();
        String escolaridad = escolaridad_niño.getText();
        String direccion = direccion_niño.getText();
        String motivo = motivo_consulta_niño.getText();
        String referencia = referencia_niño.getText();
        String diagnostico = diagnostico_niño.getText();
        String prenatar = prenatal.getText();
        String posnatar = posnatal.getText();
        String desarrollo = desarrollo_psicomotor.getText();
        String alimento = alimentacion.getText();
        String sueños = sueño.getText();
        String aseo = aseo_personal.getText();
        String emocionar = emocional.getText();
        String limitesEs = limites_establecedor.getText();
        String limitesEj = limites_ejecutor.getText();
        String actual = situacion_actual_niño.getText();
        String apariencia = apariencia_general_niño.getText();
        String recomendaciones = recomendaciones_niño.getText();
        
        if(nombre.equals("") || apellido.equals("") || edad.equals("") || lugarNacimiento.equals("") || escolaridad.equals("")
                || direccion.equals("") || motivo.equals("") || referencia.equals("") || diagnostico.equals("") || prenatar.equals("") || posnatar.equals("")
                || desarrollo.equals("") || alimento.equals("") || sueños.equals("") || aseo.equals("") || emocionar.equals("") || limitesEs.equals("")
                || limitesEj.equals("") || actual.equals("") || apariencia.equals("") || recomendaciones.equals("")){
            JOptionPane.showMessageDialog(null, "¡¡Debe llenar todos los campos!!");           
        } else{
            try{
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into historia_clinica_niños values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                
                pst.setString(1, "0");
                pst.setString(2, nombre_niño.getText().trim());
                pst.setString(3, apellido_niño.getText().trim());
                pst.setString(4, edad_niño.getText().trim());
                pst.setString(5, sexo.trim());
                pst.setString(6, lugar_nacimiento_niño.getText().trim());
                pst.setString(7, fecha.trim());
                pst.setString(8, escolaridad_niño.getText().trim());
                pst.setString(9, direccion_niño.getText().trim());
                pst.setString(10, motivo_consulta_niño.getText().trim());
                pst.setString(11, referencia_niño.getText().trim());
                pst.setString(12, diagnostico_niño.getText().trim());
                pst.setString(13, prenatal.getText().trim());
                pst.setString(14, posnatal.getText().trim());
                pst.setString(15, desarrollo_psicomotor.getText().trim());
                pst.setString(16, alimentacion.getText().trim());
                pst.setString(17, sueño.getText().trim());
                pst.setString(18, aseo_personal.getText().trim());
                pst.setString(19, emocional.getText().trim());
                pst.setString(20, limites_establecedor.getText().trim());
                pst.setString(21, limites_ejecutor.getText().trim());
                pst.setString(22, situacion_actual_niño.getText().trim());
                pst.setString(23, apariencia_general_niño.getText().trim());
                pst.setString(24, recomendaciones_niño.getText().trim());
                pst.executeUpdate();
                
                nombre_niño.setText("");
                apellido_niño.setText("");
                edad_niño.setText("");
                lugar_nacimiento_niño.setText("");
                escolaridad_niño.setText("");
                direccion_niño.setText("");
                motivo_consulta_niño.setText("");
                referencia_niño.setText("");
                diagnostico_niño.setText("");
                prenatal.setText("");
                posnatal.setText("");
                desarrollo_psicomotor.setText("");
                alimentacion.setText("");
                sueño.setText("");
                aseo_personal.setText("");
                emocional.setText("");
                limites_establecedor.setText("");
                limites_ejecutor.setText("");
                situacion_actual_niño.setText("");
                apariencia_general_niño.setText("");
                recomendaciones_niño.setText("");
                etiquetaLocas.setText("Registro completado");
                
            } catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_registrar_niñosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaNiñosCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaNiñosCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaNiñosCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaNiñosCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaNiñosCoordinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alimentacion;
    private javax.swing.JTextField apariencia_general_niño;
    private javax.swing.JTextField apellido_niño;
    private javax.swing.JTextField aseo_personal;
    private javax.swing.JTextArea desarrollo_psicomotor;
    private javax.swing.JTextArea diagnostico_niño;
    private javax.swing.JTextField direccion_niño;
    private javax.swing.JTextField edad_niño;
    private javax.swing.JTextField emocional;
    private javax.swing.JTextField escolaridad_niño;
    private javax.swing.JLabel etiquetaLoca2;
    private javax.swing.JLabel etiquetaLocas;
    private com.toedter.calendar.JDateChooser fecha_nacimiento_niños;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField limites_ejecutor;
    private javax.swing.JTextField limites_establecedor;
    private javax.swing.JTextField lugar_nacimiento_niño;
    private javax.swing.JTextArea motivo_consulta_niño;
    private javax.swing.JTextField nombre_niño;
    private javax.swing.JTextArea posnatal;
    private javax.swing.JTextArea prenatal;
    private javax.swing.JTextField recomendaciones_niño;
    private javax.swing.JTextArea referencia_niño;
    private javax.swing.JButton registrar_niños;
    private javax.swing.JButton salir_niños;
    private javax.swing.JComboBox<String> sexo_niños;
    private javax.swing.JTextArea situacion_actual_niño;
    private javax.swing.JTextField sueño;
    // End of variables declaration//GEN-END:variables
}
