/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventana.psicologo;

import ventana.director.SistemaPrincipalDiretor;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Edder
 */
public class RegistroAdultosPsicologos extends javax.swing.JFrame {

    /** Creates new form VentanaAdultos */
    public RegistroAdultosPsicologos() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/logo3.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CAPsys");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/rosa.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre_adulto_registro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido_adulto_registro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cedula_adulto_registro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edad_adulto_registro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lugar_nacimiento_adulto_registro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fecha_nacimiento_adulto_registro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ocupacion_adulto_registro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        profesion_adulto_registro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        escolaridad_adulto_registro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        direccion_adulto_registro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivo_adulto_registro = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        referencia_adulto_registro = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnostico_adulto_registro = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        antecedentes_adulto_registro = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        accesibilidad_adulto_registro = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        actividad_adulto_registro = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lenguaje_adulto_registro = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        situacion_actual_adulto_registro = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        apariencia_general_adulto_registro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        recomendaciones_adulto_registro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        sexo_adultos_registro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Datos de Identificación");

        jLabel2.setText("Nombres:");

        nombre_adulto_registro.setEditable(false);

        jLabel3.setText("Apellidos:");

        apellido_adulto_registro.setEditable(false);

        jLabel4.setText("Cedula:");

        jLabel5.setText("Edad:");

        edad_adulto_registro.setEditable(false);

        jLabel6.setText("Sexo:");

        jLabel7.setText("Lugar de Nacimiento:");

        lugar_nacimiento_adulto_registro.setEditable(false);

        jLabel8.setText("Fecha de Nacimiento:");

        fecha_nacimiento_adulto_registro.setEditable(false);

        jLabel9.setText("Ocupación:");

        ocupacion_adulto_registro.setEditable(false);

        jLabel10.setText("Profesión:");

        profesion_adulto_registro.setEditable(false);

        jLabel11.setText("Escolaridad:");

        escolaridad_adulto_registro.setEditable(false);

        jLabel12.setText("Dirección:");

        direccion_adulto_registro.setEditable(false);

        jLabel13.setText("Motivo de la Consulta:");

        motivo_adulto_registro.setEditable(false);
        motivo_adulto_registro.setColumns(20);
        motivo_adulto_registro.setLineWrap(true);
        motivo_adulto_registro.setRows(5);
        jScrollPane1.setViewportView(motivo_adulto_registro);

        jLabel14.setText("Referencia:");

        referencia_adulto_registro.setEditable(false);
        referencia_adulto_registro.setColumns(20);
        referencia_adulto_registro.setLineWrap(true);
        referencia_adulto_registro.setRows(5);
        jScrollPane2.setViewportView(referencia_adulto_registro);

        jLabel15.setText("ID(diagnostico):");

        diagnostico_adulto_registro.setEditable(false);
        diagnostico_adulto_registro.setColumns(20);
        diagnostico_adulto_registro.setLineWrap(true);
        diagnostico_adulto_registro.setRows(5);
        jScrollPane3.setViewportView(diagnostico_adulto_registro);

        jLabel16.setText("Antecedentes:");

        antecedentes_adulto_registro.setEditable(false);
        antecedentes_adulto_registro.setColumns(20);
        antecedentes_adulto_registro.setLineWrap(true);
        antecedentes_adulto_registro.setRows(5);
        jScrollPane4.setViewportView(antecedentes_adulto_registro);

        jLabel17.setText("Accesibilidad:");

        accesibilidad_adulto_registro.setEditable(false);
        accesibilidad_adulto_registro.setColumns(20);
        accesibilidad_adulto_registro.setLineWrap(true);
        accesibilidad_adulto_registro.setRows(5);
        jScrollPane5.setViewportView(accesibilidad_adulto_registro);

        jLabel18.setText("Actividad:");

        actividad_adulto_registro.setEditable(false);
        actividad_adulto_registro.setColumns(20);
        actividad_adulto_registro.setLineWrap(true);
        actividad_adulto_registro.setRows(5);
        jScrollPane6.setViewportView(actividad_adulto_registro);

        jLabel19.setText("Lenguaje:");

        lenguaje_adulto_registro.setEditable(false);
        lenguaje_adulto_registro.setColumns(20);
        lenguaje_adulto_registro.setLineWrap(true);
        lenguaje_adulto_registro.setRows(5);
        jScrollPane7.setViewportView(lenguaje_adulto_registro);

        jLabel20.setText("Situación Actual:");

        situacion_actual_adulto_registro.setEditable(false);
        situacion_actual_adulto_registro.setColumns(20);
        situacion_actual_adulto_registro.setLineWrap(true);
        situacion_actual_adulto_registro.setRows(5);
        jScrollPane8.setViewportView(situacion_actual_adulto_registro);

        jLabel21.setText("Apariencia General:");

        apariencia_general_adulto_registro.setEditable(false);

        jLabel22.setText("Recomendaciones:");

        recomendaciones_adulto_registro.setEditable(false);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        boton_salir.setBackground(new java.awt.Color(255, 153, 153));
        boton_salir.setText("Regresar");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        sexo_adultos_registro.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_nacimiento_adulto_registro)
                            .addComponent(lugar_nacimiento_adulto_registro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula_adulto_registro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edad_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(sexo_adultos_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(apellido_adulto_registro)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_adulto_registro))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccion_adulto_registro)
                            .addComponent(escolaridad_adulto_registro)
                            .addComponent(profesion_adulto_registro)
                            .addComponent(ocupacion_adulto_registro)))
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7)
                                    .addComponent(jScrollPane8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(recomendaciones_adulto_registro)
                                            .addComponent(apariencia_general_adulto_registro))))))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cedula_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellido_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edad_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(sexo_adultos_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lugar_nacimiento_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(fecha_nacimiento_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ocupacion_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(profesion_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(escolaridad_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(direccion_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel18))
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(apariencia_general_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(recomendaciones_adulto_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton_salir)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        SistemaPrincipalPsicologos ventana = new SistemaPrincipalPsicologos();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_salirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_adultos where Cedula = ?");
            
            pst.setString(1, cedula_adulto_registro.getText().trim());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                nombre_adulto_registro.setText(rs.getString("Nombres"));
                apellido_adulto_registro.setText(rs.getString("Apellidos"));
                edad_adulto_registro.setText(rs.getString("Edad"));
                sexo_adultos_registro.setText(rs.getString("Sexo"));
                lugar_nacimiento_adulto_registro.setText(rs.getString("LugarDeNacimiento"));
                fecha_nacimiento_adulto_registro.setText(rs.getString("FechaDeNacimiento"));
                ocupacion_adulto_registro.setText(rs.getString("Ocupacion"));
                profesion_adulto_registro.setText(rs.getString("Profesion"));
                escolaridad_adulto_registro.setText(rs.getString("Escolaridad"));
                direccion_adulto_registro.setText(rs.getString("Direccion"));
                motivo_adulto_registro.setText(rs.getString("MotivoConsulta"));
                referencia_adulto_registro.setText(rs.getString("Referencia"));
                diagnostico_adulto_registro.setText(rs.getString("ID(diagnostico)"));
                antecedentes_adulto_registro.setText(rs.getString("Antecedentes"));
                accesibilidad_adulto_registro.setText(rs.getString("Accesibilidad"));
                actividad_adulto_registro.setText(rs.getString("Actividad"));
                lenguaje_adulto_registro.setText(rs.getString("Lenguaje"));
                situacion_actual_adulto_registro.setText(rs.getString("SituacionActual"));
                apariencia_general_adulto_registro.setText(rs.getString("AparienciaGeneral"));
                recomendaciones_adulto_registro.setText(rs.getString("Recomendaciones"));
            } else{
                JOptionPane.showMessageDialog(null, "Este registro no existe.");
            }
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAdultosPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAdultosPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAdultosPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAdultosPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAdultosPsicologos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea accesibilidad_adulto_registro;
    private javax.swing.JTextArea actividad_adulto_registro;
    private javax.swing.JTextArea antecedentes_adulto_registro;
    private javax.swing.JTextField apariencia_general_adulto_registro;
    private javax.swing.JTextField apellido_adulto_registro;
    private javax.swing.JButton boton_salir;
    private javax.swing.JTextField cedula_adulto_registro;
    private javax.swing.JTextArea diagnostico_adulto_registro;
    private javax.swing.JTextField direccion_adulto_registro;
    private javax.swing.JTextField edad_adulto_registro;
    private javax.swing.JTextField escolaridad_adulto_registro;
    private javax.swing.JTextField fecha_nacimiento_adulto_registro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea lenguaje_adulto_registro;
    private javax.swing.JTextField lugar_nacimiento_adulto_registro;
    private javax.swing.JTextArea motivo_adulto_registro;
    private javax.swing.JTextField nombre_adulto_registro;
    private javax.swing.JTextField ocupacion_adulto_registro;
    private javax.swing.JTextField profesion_adulto_registro;
    private javax.swing.JTextField recomendaciones_adulto_registro;
    private javax.swing.JTextArea referencia_adulto_registro;
    private javax.swing.JTextField sexo_adultos_registro;
    private javax.swing.JTextArea situacion_actual_adulto_registro;
    // End of variables declaration//GEN-END:variables

}
