/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana.psicologo;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventana.VentanaUsuarios;

/**
 *
 * @author Edder
 */
public class SistemaPrincipalPsicologos extends javax.swing.JFrame {

    /**
     * Creates new form SistemaPrincipal
     */
    public SistemaPrincipalPsicologos() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/logo3.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CAPsys");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/rosa.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_hclinica = new javax.swing.JMenu();
        menu_adultos = new javax.swing.JMenuItem();
        menu_niños = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        adultos_item = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menu_registros = new javax.swing.JMenu();
        registro_adultos = new javax.swing.JMenuItem();
        registro_niños = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        salir_item = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Bienvenido a...");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("...Psicólogo.");

        menu_hclinica.setText("Historia Clínica");

        menu_adultos.setText("Adultos");
        menu_adultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_adultosActionPerformed(evt);
            }
        });
        menu_hclinica.add(menu_adultos);

        menu_niños.setText("Niños");
        menu_niños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_niñosActionPerformed(evt);
            }
        });
        menu_hclinica.add(menu_niños);

        jMenuBar1.add(menu_hclinica);

        jMenu2.setText("Citas");

        adultos_item.setText("Adultos");
        adultos_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultos_itemActionPerformed(evt);
            }
        });
        jMenu2.add(adultos_item);

        jMenuItem2.setText("Niños");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator1);

        jMenuItem4.setText("Cronograma de Adultos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Cronograma de Niños");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        menu_registros.setText("Registros");

        registro_adultos.setText("Adultos");
        registro_adultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registro_adultosActionPerformed(evt);
            }
        });
        menu_registros.add(registro_adultos);

        registro_niños.setText("Niños");
        registro_niños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registro_niñosActionPerformed(evt);
            }
        });
        menu_registros.add(registro_niños);

        jMenuBar1.add(menu_registros);

        jMenu1.setText("Opciones");

        jMenu6.setText("Acerca de");

        jMenuItem6.setText("El creador");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenu1.add(jMenu6);

        salir_item.setText("Salir");
        salir_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_itemActionPerformed(evt);
            }
        });
        jMenu1.add(salir_item);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_adultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_adultosActionPerformed
        VentanaAdultosPsicologos ventana = new VentanaAdultosPsicologos();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_adultosActionPerformed

    private void menu_niñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_niñosActionPerformed
        VentanaNiñosPsicologos ventana = new VentanaNiñosPsicologos();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_niñosActionPerformed

    private void registro_adultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registro_adultosActionPerformed
        RegistroAdultosPsicologos ventana = new RegistroAdultosPsicologos();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_registro_adultosActionPerformed

    private void registro_niñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registro_niñosActionPerformed
        RegistroNiñosPsicologos ventana = new RegistroNiñosPsicologos();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_registro_niñosActionPerformed

    private void salir_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_itemActionPerformed
        VentanaUsuarios ventana = new VentanaUsuarios();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_salir_itemActionPerformed

    private void adultos_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultos_itemActionPerformed
        CitasAdultosPsicologo ventana = new CitasAdultosPsicologo();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_adultos_itemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CitasNiñosPsicologo ventana = new CitasNiñosPsicologo();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CitasAdultoVistaPsicologo ventana = new CitasAdultoVistaPsicologo();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CitasNiñosVistaPsicologo ventana = new CitasNiñosVistaPsicologo();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JOptionPane.showMessageDialog(null, "Desarrollado por Elcrack2303");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaPrincipalPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaPrincipalPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaPrincipalPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaPrincipalPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaPrincipalPsicologos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adultos_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menu_adultos;
    private javax.swing.JMenu menu_hclinica;
    private javax.swing.JMenuItem menu_niños;
    private javax.swing.JMenu menu_registros;
    private javax.swing.JMenuItem registro_adultos;
    private javax.swing.JMenuItem registro_niños;
    private javax.swing.JMenuItem salir_item;
    // End of variables declaration//GEN-END:variables
}
