/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventana.psicologo;

import java.sql.*;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventana.secretaria.SistemaPrincipalSecretaria;

/**
 *
 * @author Edder
 */
public class VentanaAdultosPsicologos extends javax.swing.JFrame {

    /** Creates new form VentanaAdultos */
    public VentanaAdultosPsicologos() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/logo3.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CAPsys");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/rosa.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre_adulto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido_adulto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cedula_adulto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edad_adulto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caja_sexo_adulto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lugar_nacimiento_adulto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ocupacion_adulto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        profesion_adulto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        escolaridad_adulto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        direccion_adulto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivo_adulto = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        referencia_adulto = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnostico_adulto = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        antecedentes_adulto = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        accesibilidad_adulto = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        actividad_adulto = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lenguaje_adulto = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        situacion_actual_adulto = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        apariencia_general_adulto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        recomendaciones_adulto = new javax.swing.JTextField();
        boton_registrar = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        etiquetaLoca = new javax.swing.JLabel();
        etiquetaLocas = new javax.swing.JLabel();
        fecha_nacimiento_adulto = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Datos de Identificación");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Cedula:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Sexo:");

        caja_sexo_adulto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        jLabel7.setText("Lugar de Nacimiento:");

        jLabel8.setText("Fecha de Nacimiento:");

        jLabel9.setText("Ocupación:");

        jLabel10.setText("Profesión:");

        jLabel11.setText("Escolaridad:");

        jLabel12.setText("Dirección:");

        jLabel13.setText("Motivo de la Consulta:");

        motivo_adulto.setColumns(20);
        motivo_adulto.setLineWrap(true);
        motivo_adulto.setRows(5);
        jScrollPane1.setViewportView(motivo_adulto);

        jLabel14.setText("Referencia:");

        referencia_adulto.setColumns(20);
        referencia_adulto.setLineWrap(true);
        referencia_adulto.setRows(5);
        jScrollPane2.setViewportView(referencia_adulto);

        jLabel15.setText("ID(diagnostico):");

        diagnostico_adulto.setColumns(20);
        diagnostico_adulto.setLineWrap(true);
        diagnostico_adulto.setRows(5);
        jScrollPane3.setViewportView(diagnostico_adulto);

        jLabel16.setText("Antecedentes:");

        antecedentes_adulto.setColumns(20);
        antecedentes_adulto.setLineWrap(true);
        antecedentes_adulto.setRows(5);
        jScrollPane4.setViewportView(antecedentes_adulto);

        jLabel17.setText("Accesibilidad:");

        accesibilidad_adulto.setColumns(20);
        accesibilidad_adulto.setLineWrap(true);
        accesibilidad_adulto.setRows(5);
        jScrollPane5.setViewportView(accesibilidad_adulto);

        jLabel18.setText("Actividad:");

        actividad_adulto.setColumns(20);
        actividad_adulto.setLineWrap(true);
        actividad_adulto.setRows(5);
        jScrollPane6.setViewportView(actividad_adulto);

        jLabel19.setText("Lenguaje:");

        lenguaje_adulto.setColumns(20);
        lenguaje_adulto.setLineWrap(true);
        lenguaje_adulto.setRows(5);
        jScrollPane7.setViewportView(lenguaje_adulto);

        jLabel20.setText("Situación Actual:");

        situacion_actual_adulto.setColumns(20);
        situacion_actual_adulto.setLineWrap(true);
        situacion_actual_adulto.setRows(5);
        jScrollPane8.setViewportView(situacion_actual_adulto);

        jLabel21.setText("Apariencia General:");

        jLabel22.setText("Recomendaciones:");

        boton_registrar.setBackground(new java.awt.Color(255, 153, 153));
        boton_registrar.setText("Registrar");
        boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrarActionPerformed(evt);
            }
        });

        boton_salir.setBackground(new java.awt.Color(255, 153, 153));
        boton_salir.setText("Regresar");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        etiquetaLocas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lugar_nacimiento_adulto)
                            .addComponent(fecha_nacimiento_adulto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula_adulto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edad_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caja_sexo_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 75, Short.MAX_VALUE))
                            .addComponent(apellido_adulto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_adulto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccion_adulto)
                            .addComponent(escolaridad_adulto)
                            .addComponent(profesion_adulto)
                            .addComponent(ocupacion_adulto)))
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7)
                                    .addComponent(jScrollPane8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(etiquetaLoca)
                                            .addComponent(etiquetaLocas))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(recomendaciones_adulto)
                                            .addComponent(apariencia_general_adulto))))))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellido_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cedula_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edad_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(caja_sexo_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lugar_nacimiento_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(fecha_nacimiento_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ocupacion_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(profesion_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(escolaridad_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(direccion_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel18))
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(apariencia_general_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(recomendaciones_adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton_registrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boton_salir)
                                    .addComponent(etiquetaLoca)
                                    .addComponent(etiquetaLocas))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        SistemaPrincipalPsicologos ventana = new SistemaPrincipalPsicologos();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_salirActionPerformed

    private void boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrarActionPerformed
        
        String sexo = (String) caja_sexo_adulto.getSelectedItem();
        Date date = fecha_nacimiento_adulto.getDate();
        long d = date.getTime();
        java.sql.Date date2 = new java.sql.Date(d);
        String fecha = date2.toString();
        
        String nombre = nombre_adulto.getText();
        String apellido = apellido_adulto.getText();
        String cedula = cedula_adulto.getText();
        String edad = edad_adulto.getText();
        String lugarNacimiento = lugar_nacimiento_adulto.getText();
        String ocupacion = ocupacion_adulto.getText();
        String profesion = profesion_adulto.getText();
        String escolaridad = escolaridad_adulto.getText();
        String direccion = direccion_adulto.getText();
        String motivo = motivo_adulto.getText();
        String referencia = referencia_adulto.getText();
        String diagnostico = diagnostico_adulto.getText();
        String antecedentes = antecedentes_adulto.getText();
        String accesibilidad = accesibilidad_adulto.getText();
        String actividad = actividad_adulto.getText();
        String lenguaje = lenguaje_adulto.getText();
        String actual = situacion_actual_adulto.getText();
        String apariencia = apariencia_general_adulto.getText();
        String recomendaciones = recomendaciones_adulto.getText();
        
        if(nombre.equals("") || apellido.equals("") || cedula.equals("") || edad.equals("") || lugarNacimiento.equals("") 
                || ocupacion.equals("") ||  escolaridad.equals("") || direccion.equals("") || motivo.equals("") || referencia.equals("")
                || diagnostico.equals("") || antecedentes.equals("") || accesibilidad.equals("") || actividad.equals("") || lenguaje.equals("") || actual.equals("")
                || apariencia.equals("") || recomendaciones.equals("") || profesion.equals("")){
            JOptionPane.showMessageDialog(null, "¡¡Debe llenar todos los campos!!");
        }else{
            try{
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into historia_clinica_adultos values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
                pst.setString(1, nombre_adulto.getText().trim());
                pst.setString(2, apellido_adulto.getText().trim());
                pst.setString(3, cedula_adulto.getText().trim());
                pst.setString(4, edad_adulto.getText().trim());
                pst.setString(5, sexo.trim());
                pst.setString(6, lugar_nacimiento_adulto.getText().trim());
                pst.setString(7, fecha.trim());
                pst.setString(8, ocupacion_adulto.getText().trim());
                pst.setString(9, profesion_adulto.getText().trim());
                pst.setString(10, escolaridad_adulto.getText().trim());
                pst.setString(11, direccion_adulto.getText().trim());
                pst.setString(12, motivo_adulto.getText().trim());
                pst.setString(13, referencia_adulto.getText().trim());
                pst.setString(14, diagnostico_adulto.getText().trim());
                pst.setString(15, antecedentes_adulto.getText().trim());
                pst.setString(16, accesibilidad_adulto.getText().trim());
                pst.setString(17, actividad_adulto.getText().trim());
                pst.setString(18, lenguaje_adulto.getText().trim());
                pst.setString(19, situacion_actual_adulto.getText().trim());
                pst.setString(20, apariencia_general_adulto.getText().trim());
                pst.setString(21, recomendaciones_adulto.getText().trim());
                pst.executeUpdate();
            
                nombre_adulto.setText("");
                apellido_adulto.setText("");
                cedula_adulto.setText("");
                edad_adulto.setText("");
                lugar_nacimiento_adulto.setText("");
                ocupacion_adulto.setText("");
                profesion_adulto.setText("");
                escolaridad_adulto.setText("");
                direccion_adulto.setText("");
                motivo_adulto.setText("");
                referencia_adulto.setText("");
                diagnostico_adulto.setText("");
                antecedentes_adulto.setText("");
                accesibilidad_adulto.setText("");
                actividad_adulto.setText("");
                lenguaje_adulto.setText("");
                situacion_actual_adulto.setText("");
                apariencia_general_adulto.setText("");
                recomendaciones_adulto.setText("");
                etiquetaLocas.setText("Registro completado");
            
            } catch(Exception e){
            
            }
        }
    }//GEN-LAST:event_boton_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdultosPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdultosPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdultosPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdultosPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdultosPsicologos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea accesibilidad_adulto;
    private javax.swing.JTextArea actividad_adulto;
    private javax.swing.JTextArea antecedentes_adulto;
    private javax.swing.JTextField apariencia_general_adulto;
    private javax.swing.JTextField apellido_adulto;
    private javax.swing.JButton boton_registrar;
    private javax.swing.JButton boton_salir;
    private javax.swing.JComboBox<String> caja_sexo_adulto;
    private javax.swing.JTextField cedula_adulto;
    private javax.swing.JTextArea diagnostico_adulto;
    private javax.swing.JTextField direccion_adulto;
    private javax.swing.JTextField edad_adulto;
    private javax.swing.JTextField escolaridad_adulto;
    private javax.swing.JLabel etiquetaLoca;
    private javax.swing.JLabel etiquetaLocas;
    private com.toedter.calendar.JDateChooser fecha_nacimiento_adulto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea lenguaje_adulto;
    private javax.swing.JTextField lugar_nacimiento_adulto;
    private javax.swing.JTextArea motivo_adulto;
    private javax.swing.JTextField nombre_adulto;
    private javax.swing.JTextField ocupacion_adulto;
    private javax.swing.JTextField profesion_adulto;
    private javax.swing.JTextField recomendaciones_adulto;
    private javax.swing.JTextArea referencia_adulto;
    private javax.swing.JTextArea situacion_actual_adulto;
    // End of variables declaration//GEN-END:variables

}
