/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana.director;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventana.director.SistemaPrincipalDiretor;

/**
 *
 * @author Edder
 */
public class CitasNiñosDirector extends javax.swing.JFrame {

    /**
     * Creates new form CitasAdultos
     */
    public CitasNiñosDirector() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/logo3.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CAPsys");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/rosa.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        combo_pacientes.removeAllItems();
        combo_pacientes.addItem("");
        combo_especialistas.removeAllItems();
        combo_especialistas.addItem("");
        ArrayList<String> lista = new ArrayList<String>();
        lista = llenarPacientes();
        for (int i = 0; i < lista.size(); i++) {
            combo_pacientes.addItem(lista.get(i));
        }
        lista = llenarEspe();
        for (int i = 0; i < lista.size(); i++) {
            combo_especialistas.addItem(lista.get(i));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombre_paciente = new javax.swing.JTextField();
        apellido_paciente = new javax.swing.JTextField();
        cedula_paciente = new javax.swing.JTextField();
        nombre_especialista = new javax.swing.JTextField();
        apellido_especialista = new javax.swing.JTextField();
        cedula_especialista = new javax.swing.JTextField();
        combo_pacientes = new javax.swing.JComboBox<>();
        combo_especialistas = new javax.swing.JComboBox<>();
        fecha_cita = new com.toedter.calendar.JDateChooser();
        boton_regresar = new javax.swing.JButton();
        boton_registrar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        etiquetaLoca = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sexo_paciente = new javax.swing.JTextField();
        etiquetazo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pacientes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Paciente:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombres:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cedula:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Especialistas");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Especialista:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nombres:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Apellidos:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cedula:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Fecha de la Cita:");

        nombre_paciente.setEditable(false);

        apellido_paciente.setEditable(false);

        cedula_paciente.setEditable(false);

        nombre_especialista.setEditable(false);

        cedula_especialista.setEditable(false);

        combo_pacientes.setBackground(new java.awt.Color(255, 153, 153));
        combo_pacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_pacientesActionPerformed(evt);
            }
        });

        combo_especialistas.setBackground(new java.awt.Color(255, 153, 153));
        combo_especialistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_especialistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_especialistasActionPerformed(evt);
            }
        });

        fecha_cita.setBackground(new java.awt.Color(255, 153, 153));

        boton_regresar.setBackground(new java.awt.Color(255, 153, 153));
        boton_regresar.setText("Regresar");
        boton_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_regresarActionPerformed(evt);
            }
        });

        boton_registrar.setBackground(new java.awt.Color(255, 153, 153));
        boton_registrar.setText("Registrar");
        boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        etiquetaLoca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Sexo:");

        sexo_paciente.setEditable(false);

        etiquetazo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boton_registrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_regresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_especialistas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cedula_especialista)
                            .addComponent(apellido_especialista)
                            .addComponent(nombre_especialista)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha_cita, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_pacientes, 0, 200, Short.MAX_VALUE)
                            .addComponent(cedula_paciente)
                            .addComponent(apellido_paciente)
                            .addComponent(nombre_paciente)
                            .addComponent(sexo_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiquetaLoca))
                            .addComponent(jLabel6)
                            .addComponent(etiquetazo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(combo_pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cedula_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sexo_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(combo_especialistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nombre_especialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(apellido_especialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cedula_especialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addComponent(fecha_cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(etiquetaLoca))
                .addGap(18, 18, 18)
                .addComponent(etiquetazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_registrar)
                    .addComponent(boton_regresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_pacientesActionPerformed
        try {
            String item = (String) combo_pacientes.getSelectedItem();
            String cedula = item.substring(0,5);
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica","root","");
            PreparedStatement pst = cn.prepareStatement("Select * from historia_clinica_niños where Indice = ?");
            
            pst.setString(1, cedula.trim());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                nombre_paciente.setText(rs.getString("Nombres"));
                apellido_paciente.setText(rs.getString("Apellidos"));
                cedula_paciente.setText(rs.getString("Indice"));
                sexo_paciente.setText(rs.getString("Sexo"));
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combo_pacientesActionPerformed

    private void combo_especialistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_especialistasActionPerformed
        try {
            String item = (String) combo_especialistas.getSelectedItem();
            String cedula = item.substring(0,8);
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica","root","");
            PreparedStatement pst = cn.prepareStatement("Select * from especialistas where Cedula = ?");
            
            pst.setString(1, cedula.trim());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                nombre_especialista.setText(rs.getString("Nombres"));
                apellido_especialista.setText(rs.getString("Apellidos"));
                cedula_especialista.setText(rs.getString("Cedula"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combo_especialistasActionPerformed

    private void boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrarActionPerformed
        java.util.Date date = fecha_cita.getDate();
        long d = date.getTime();
        java.sql.Date date2 = new java.sql.Date(d);
        String fecha = date2.toString();   
        String nombre = nombre_paciente.getText();
        String cedulaE = cedula_especialista.getText();
        if(nombre.equals("") || cedulaE.equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar paciente y/o especialista.");
        } else{
            try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into registro_citas_niños values(?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1, "0");
            pst.setString(2, nombre_paciente.getText().trim());
            pst.setString(3, apellido_paciente.getText().trim());
            pst.setString(4, cedula_paciente.getText().trim());
            pst.setString(5, sexo_paciente.getText().trim());
            pst.setString(6, nombre_especialista.getText().trim());
            pst.setString(7, apellido_especialista.getText().trim());
            pst.setString(8, cedula_especialista.getText().trim());
            pst.setString(9, fecha.trim());
            pst.executeUpdate();
            
            etiquetazo.setText("Registro Exitoso");
        } catch(Exception e){
            
        }
        }
    }//GEN-LAST:event_boton_registrarActionPerformed

    private void boton_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_regresarActionPerformed
        SistemaPrincipalDiretor ventana = new SistemaPrincipalDiretor();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitasNiñosDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitasNiñosDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitasNiñosDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitasNiñosDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitasNiñosDirector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido_especialista;
    private javax.swing.JTextField apellido_paciente;
    private javax.swing.JButton boton_registrar;
    private javax.swing.JButton boton_regresar;
    private javax.swing.JTextField cedula_especialista;
    private javax.swing.JTextField cedula_paciente;
    private javax.swing.JComboBox<String> combo_especialistas;
    private javax.swing.JComboBox<String> combo_pacientes;
    private javax.swing.JLabel etiquetaLoca;
    private javax.swing.JLabel etiquetazo;
    private com.toedter.calendar.JDateChooser fecha_cita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre_especialista;
    private javax.swing.JTextField nombre_paciente;
    private javax.swing.JTextField sexo_paciente;
    // End of variables declaration//GEN-END:variables

public static ArrayList<String> llenarPacientes(){
    ArrayList<String> lista = new ArrayList<String>();
    try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica","root","");
        PreparedStatement pst = cn.prepareStatement("Select * from historia_clinica_niños");
        
        ResultSet rs = pst.executeQuery();
        
        while(rs.next()){
            lista.add(rs.getString("Indice") + "    " + rs.getString("Nombres"));
        }
    } catch (Exception e) {
    }
    
    return lista;
}
public static ArrayList<String> llenarEspe(){
    ArrayList<String> lista = new ArrayList<String>();
    try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica","root","");
        PreparedStatement pst = cn.prepareStatement("Select * from especialistas");
        
        ResultSet rs = pst.executeQuery();
        
        while(rs.next()){
            lista.add(rs.getString("Cedula") + " " + rs.getString("Nombres"));
        }
    } catch (Exception e) {
    }
    
    return lista;
}
}
