/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana.director;

import java.util.ArrayList;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventana.director.SistemaPrincipalDiretor;

/**
 *
 * @author Edder
 */
public class EstadísticasDirector extends javax.swing.JFrame {

    /**
     * Creates new form Estadísticas
     */
    public EstadísticasDirector() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/logo3.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CAPsys");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/rosa.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        combo_especialistas.removeAllItems();
        combo_especialistas.addItem("");
        ArrayList<String> lista = new ArrayList<String>();
        lista = llenarEspe();
        for (int i = 0; i < lista.size(); i++) {
            combo_especialistas.addItem(lista.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combo_especialistas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        especialista = new javax.swing.JTextField();
        boton_buscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        niños = new javax.swing.JTextField();
        adultos = new javax.swing.JTextField();
        hombres = new javax.swing.JTextField();
        mujeres = new javax.swing.JTextField();
        niñas_mujeres = new javax.swing.JTextField();
        niños_hombres = new javax.swing.JTextField();
        mujeresfull = new javax.swing.JTextField();
        hombresfull = new javax.swing.JTextField();
        adultos_total = new javax.swing.JTextField();
        niños_total = new javax.swing.JTextField();
        mujeres_total = new javax.swing.JTextField();
        hombres_total = new javax.swing.JTextField();
        niñas_total = new javax.swing.JTextField();
        hembras_total = new javax.swing.JTextField();
        varones_total = new javax.swing.JTextField();
        machos_total = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pacientes_totales = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel20.setText("jLabel20");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Estadísticas");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pacientes niños atendidos:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Pacientes adultos atendidos:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Pacientes femeninos:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Pacientes masculinos:");

        combo_especialistas.setBackground(new java.awt.Color(255, 153, 153));
        combo_especialistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Atendió:");

        especialista.setEditable(false);

        boton_buscar.setBackground(new java.awt.Color(255, 153, 153));
        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pacientes niños totales:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pacientes adultos totales");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Pacientes femeninos totales:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Pacientes masculinos totales:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Pacientes niños femeninos totales:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Pacientes adultos femeninos totales:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Pacientes niños masculinos totales:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Pacientes adultos masculinos totales:");

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Pacientes niños femeninos:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Pacientes niños masculinos:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Pacientes adultos femeninos:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Pacientes adultos masculinos:");

        niños.setEditable(false);

        adultos.setEditable(false);

        hombres.setEditable(false);

        mujeres.setEditable(false);

        niñas_mujeres.setEditable(false);

        niños_hombres.setEditable(false);

        mujeresfull.setEditable(false);

        hombresfull.setEditable(false);

        adultos_total.setEditable(false);

        niños_total.setEditable(false);

        mujeres_total.setEditable(false);

        hombres_total.setEditable(false);

        niñas_total.setEditable(false);

        hembras_total.setEditable(false);

        varones_total.setEditable(false);

        machos_total.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Pacientes totales:");

        pacientes_totales.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(boton_buscar)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(combo_especialistas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(especialista, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(niños, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adultos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(niñas_mujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(niños_hombres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mujeresfull, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hombresfull, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hombres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varones_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(niños_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(adultos_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mujeres_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hombres_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(niñas_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hembras_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(machos_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pacientes_totales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 27, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(especialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(combo_especialistas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(niños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(adultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(mujeres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(hombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(niñas_mujeres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(niños_hombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(mujeresfull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(hombresfull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(niños_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(adultos_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(mujeres_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(hombres_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(niñas_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(hembras_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(varones_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(machos_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(pacientes_totales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        String cadena1 = (String) combo_especialistas.getSelectedItem();
        if(cadena1.equals("")){
            JOptionPane.showMessageDialog(null, "Debe elegir un especialista.");
        } else{
            String item = (String) combo_especialistas.getSelectedItem();
        String cedula = item.substring(0,8);
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_niños where CedulaEspecialista = ?");
            
            pst.setString(1, cedula.trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            niños.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_adultos where CedulaEspecialista = ?");
            
            pst.setString(1, cedula.trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            adultos.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero1 = 0;
            int numero2 = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_adultos where CedulaEspecialista = ?");
            Connection cno = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pstn = cn.prepareStatement("select * from registro_citas_niños where CedulaEspecialista = ?");
            
            pst.setString(1, cedula.trim());
            pstn.setString(1, cedula.trim());
            
            ResultSet rs = pst.executeQuery();
            ResultSet rst = pstn.executeQuery();
            
            while(rs.next()){
                numero1++;
            }
            while(rst.next()){
                numero2++;
            }
            int resultado = numero1 + numero2;
            String cadena = Integer.toString(resultado);
            especialista.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero1 = 0, numero2 = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_adultos where CedulaEspecialista = ? and SexoPaciente = ?");
            Connection cno = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pstn = cn.prepareStatement("select * from registro_citas_niños where CedulaEspecialista = ? and SexoPaciente = ?");
            
            pst.setString(1, cedula.trim());
            pst.setString(2, "F".trim());
            pstn.setString(1, cedula.trim());
            pstn.setString(2, "F".trim());
            
            ResultSet rs = pst.executeQuery();
            ResultSet rst = pstn.executeQuery();
            
            while(rs.next()){
                numero1++;
            }
            while(rst.next()){
                numero2++;
            }
            int resultado = numero1 + numero2;
            String cadena = Integer.toString(resultado);
            mujeres.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero1 = 0, numero2 = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_adultos where CedulaEspecialista = ? and SexoPaciente = ?");
            Connection cno = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pstn = cn.prepareStatement("select * from registro_citas_niños where CedulaEspecialista = ? and SexoPaciente = ?");
            
            pst.setString(1, cedula.trim());
            pst.setString(2, "M".trim());
            pstn.setString(1, cedula.trim());
            pstn.setString(2, "M".trim());
            
            ResultSet rs = pst.executeQuery();
            ResultSet rst = pstn.executeQuery();
            
            while(rs.next()){
                numero1++;
            }
            while(rst.next()){
                numero2++;
            }
            int resultado = numero1 + numero2;
            String cadena = Integer.toString(resultado);
            hombres.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_niños where CedulaEspecialista = ? and SexoPaciente = ?");
            pst.setString(1, cedula.trim());
            pst.setString(2, "F".trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            niñas_mujeres.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_niños where CedulaEspecialista = ? and SexoPaciente = ?");
            pst.setString(1, cedula.trim());
            pst.setString(2, "M".trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            niños_hombres.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_adultos where CedulaEspecialista = ? and SexoPaciente = ?");
            pst.setString(1, cedula.trim());
            pst.setString(2, "F".trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            mujeresfull.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from registro_citas_adultos where CedulaEspecialista = ? and SexoPaciente = ?");
            pst.setString(1, cedula.trim());
            pst.setString(2, "M".trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            hombresfull.setText(cadena);
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SistemaPrincipalDiretor ventana = new SistemaPrincipalDiretor();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_niños");
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            niños_total.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_adultos");
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            adultos_total.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero1 = 0, numero2 = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_niños where Sexo = ?");
            Connection cnn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pstn = cn.prepareStatement("select * from historia_clinica_adultos where Sexo = ?");
            
            pst.setString(1, "F".trim());
            pstn.setString(1, "F".trim());
            
            ResultSet rs = pst.executeQuery();
            ResultSet rst = pstn.executeQuery();
            
            while(rs.next()){
                numero1++;
            }
            while(rst.next()){
                numero2++;
            }
            int resultado = numero1 + numero2;
            String cadena = Integer.toString(resultado);
            mujeres_total.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero1 = 0, numero2 = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_niños where Sexo = ?");
            Connection cnn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pstn = cn.prepareStatement("select * from historia_clinica_adultos where Sexo = ?");
            
            pst.setString(1, "M".trim());
            pstn.setString(1, "M".trim());
            
            ResultSet rs = pst.executeQuery();
            ResultSet rst = pstn.executeQuery();
            
            while(rs.next()){
                numero1++;
            }
            while(rst.next()){
                numero2++;
            }
            int resultado = numero1 + numero2;
            String cadena = Integer.toString(resultado);
            hombres_total.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_niños where Sexo = ?");
            
            pst.setString(1, "F".trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            niñas_total.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_adultos where Sexo = ?");
            
            pst.setString(1, "F".trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            hembras_total.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_niños where Sexo = ?");
            
            pst.setString(1, "M".trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            varones_total.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_adultos where Sexo = ?");
            
            pst.setString(1, "M".trim());
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                numero++;
            }
            String cadena = Integer.toString(numero);
            machos_total.setText(cadena);
        } catch (Exception e) {
        }
        try {
            int numero1 = 0, numero2 = 0;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from historia_clinica_niños");
            Connection cnn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica", "root", "");
            PreparedStatement pstn = cn.prepareStatement("select * from historia_clinica_adultos");
            
            ResultSet rs = pst.executeQuery();
            ResultSet rst = pstn.executeQuery();
            
            while(rs.next()){
                numero1++;
            }
            while(rst.next()){
                numero2++;
            }
            int resultado = numero1 + numero2;
            String cadena = Integer.toString(resultado);
            pacientes_totales.setText(cadena);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadísticasDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadísticasDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadísticasDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadísticasDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadísticasDirector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adultos;
    private javax.swing.JTextField adultos_total;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JComboBox<String> combo_especialistas;
    private javax.swing.JTextField especialista;
    private javax.swing.JTextField hembras_total;
    private javax.swing.JTextField hombres;
    private javax.swing.JTextField hombres_total;
    private javax.swing.JTextField hombresfull;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField machos_total;
    private javax.swing.JTextField mujeres;
    private javax.swing.JTextField mujeres_total;
    private javax.swing.JTextField mujeresfull;
    private javax.swing.JTextField niñas_mujeres;
    private javax.swing.JTextField niñas_total;
    private javax.swing.JTextField niños;
    private javax.swing.JTextField niños_hombres;
    private javax.swing.JTextField niños_total;
    private javax.swing.JTextField pacientes_totales;
    private javax.swing.JTextField varones_total;
    // End of variables declaration//GEN-END:variables

public static ArrayList<String> llenarEspe(){
    ArrayList<String> lista = new ArrayList<String>();
    try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/centro_atencion_psicologica","root","");
        PreparedStatement pst = cn.prepareStatement("Select * from especialistas");
        
        ResultSet rs = pst.executeQuery();
        
        while(rs.next()){
            lista.add(rs.getString("Cedula") + " " + rs.getString("Nombres"));
        }
    } catch (Exception e) {
    }
    
    return lista;
}
}
